<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-46COAO3" failures="1" tests="2" name="Default test(failed)(failed)" time="54.446" errors="0" timestamp="2023-01-09T15:46:54 IST">
  <testcase classname="TestCases.FailedTest" name="Test5" time="0.216">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FailedTest.Test5(FailedTest.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test5 -->
  <testcase classname="TestCases.FailedTest" name="Test3" time="0.069"/>
  <testcase classname="TestCases.FailedTest" name="Test1" time="0.0">
    <ignored/>
  </testcase> <!-- Test1 -->
  <testcase classname="TestCases.FailedTest" name="Test2" time="0.0">
    <ignored/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestCases.FailedTest" name="Test4" time="0.0">
    <ignored/>
  </testcase> <!-- Test4 -->
</testsuite> <!-- Default test(failed)(failed) -->
